services:
    dev:
        build:
            context: .
            dockerfile: .devcontainer/Dockerfile
        command: sleep infinity
        ports:
            - "3000:3000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: local-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: tarpaulin
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
